version: '3.8'

services:
  databricks_simulator:
    build: .
    image: aml_pipeline_simulator
    container_name: aml_databricks_simulator
    ports:
      - "8888:8888"
      - "4040:4040" # Spark UI
    volumes:
      - .:/home/jovyan/work/  # Montar repo local para persistir cambios y tablas Delta
    environment:
      - JUPYTER_ENABLE_LAB=yes
      # Puedes poner aquí variables de entorno adicionales si las necesitas
    command: start-notebook.sh --NotebookApp.token='aml_token' --NotebookApp.password=''
